language: python

cache: pip
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true

install:
  - pip install tox coverage coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coverage report -m
  - coveralls

notifications:
  email:
    recipients:
      - team@arabel.la
