language: python

cache: pip
sudo: false

python:
  - "3.5"
  - "3.6"

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-flake8

    - python: 3.5
      env: TOXENV=py35-django1.11-drf3.5
    - python: 3.5
      env: TOXENV=py35-django1.11-drf3.6
    - python: 3.5
      env: TOXENV=py35-django1.11-drf3.7
    - python: 3.5
      env: TOXENV=py35-django1.11-drf3.8

    - python: 3.6
      env: TOXENV=py36-django1.11-drf3.5
    - python: 3.6
      env: TOXENV=py36-django1.11-drf3.6
    - python: 3.6
      env: TOXENV=py36-django1.11-drf3.7
    - python: 3.6
      env: TOXENV=py36-django1.11-drf3.8

install:
  - pip install tox coverage coveralls

script:
  - tox

after_success:
  - coverage report -m
  - coveralls

notifications:
  email:
    recipients:
      - team@arabel.la
